##
## @generated by muntjac
##

load("@prelude//python:python_library.bzl", "prebuilt_python_library")
load("@prelude//utils:utils.bzl", "expect")

_CONFIGS = [
    "py311-linux-x86_64-gnu",
    "py312-linux-x86_64-gnu",
]

def pypi_package(name, version, wheels, deps = [], visibility = None, **kwargs):
    expect(set(wheels.keys()).issubset(set(_CONFIGS)),
           "unknown config in {}".format(name))

    for cfg, (url, sha256) in wheels.items():
        http_file(
            name = "{}-{}-{}-wheel".format(name, version, cfg),
            sha256 = sha256.removeprefix("sha256:"),
            urls = [url],
            visibility = [],
        )
        prebuilt_python_library(
            name = "{}-{}__{}".format(name, version, cfg),
            binary_src = ":{}-{}-{}-wheel".format(name, version, cfg),
            deps = deps,
            visibility = [],
        )

    native.alias(
        name = "{}-{}".format(name, version),
        actual = select({
            "//third-party/python/config:{}".format(cfg): ":{}-{}__{}".format(name, version, cfg)
            for cfg in wheels.keys()
        }),
        visibility = [],
    )
    native.alias(
        name = name,
        actual = ":{}-{}".format(name, version),
        visibility = visibility or ["PUBLIC"],
    )
