//! Hand-rolled string-writer implementation of `BuckEmitter`.

use std::fmt::Write;

use super::emit::{BuckEmitter, EmitInput, EmitOutput, EmitPackage};

pub struct StringTemplateEmitter;

impl BuckEmitter for StringTemplateEmitter {
    fn emit(&self, input: &EmitInput) -> EmitOutput {
        EmitOutput {
            buck: emit_buck(input),
            muntjac_bzl: String::new(),
            config_buck: String::new(),
            package_file: String::new(),
        }
    }
}

fn emit_buck(input: &EmitInput) -> String {
    let mut s = String::new();
    writeln!(s, "##").unwrap();
    writeln!(s, "## @generated by muntjac").unwrap();
    writeln!(s, "## Do not edit by hand.").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "load(\"//{}:muntjac.bzl\", \"pypi_package\")",
        input.third_party_dir
    ).unwrap();

    // Packages are pre-sorted by (name, version) in EmitInput; defensive sort anyway.
    let mut sorted_pkgs: Vec<&EmitPackage> = input.packages.iter().collect();
    sorted_pkgs.sort_by(|a, b| a.name.cmp(&b.name).then(a.version.cmp(&b.version)));

    for pkg in sorted_pkgs {
        writeln!(s).unwrap();
        write_pypi_package(&mut s, pkg);
    }
    s
}

fn write_pypi_package(s: &mut String, pkg: &EmitPackage) {
    writeln!(s, "pypi_package(").unwrap();
    writeln!(s, "    name = \"{}\",", pkg.name).unwrap();
    writeln!(s, "    version = \"{}\",", pkg.version).unwrap();
    if pkg.deps.is_empty() {
        writeln!(s, "    deps = [],").unwrap();
    } else {
        writeln!(s, "    deps = [").unwrap();
        for dep in &pkg.deps {
            writeln!(s, "        \"{}\",", dep).unwrap();
        }
        writeln!(s, "    ],").unwrap();
    }
    writeln!(s, "    wheels = {{").unwrap();
    for (cfg, wheel) in &pkg.wheels {
        writeln!(
            s,
            "        \"{}\": (\"{}\", \"{}\"),",
            cfg, wheel.url, wheel.hash
        ).unwrap();
    }
    writeln!(s, "    }},").unwrap();
    writeln!(s, "    visibility = [\"PUBLIC\"],").unwrap();
    writeln!(s, ")").unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::buck::emit::ConfigName;
    use std::collections::BTreeMap;
    use crate::buck::emit::{EmitPackage, EmitWheel};

    fn empty_input() -> EmitInput {
        EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![ConfigName::new("3.12", "linux-x86_64-gnu")],
            packages: vec![],
        }
    }

    fn single_package_input() -> EmitInput {
        let cfg = ConfigName::new("3.12", "linux-x86_64-gnu");
        let mut wheels = BTreeMap::new();
        wheels.insert(cfg.clone(), EmitWheel {
            url: "https://files.pythonhosted.org/p/certifi-2025.4.26-py3-none-any.whl".into(),
            hash: "sha256:0123abcd".into(),
        });
        EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![cfg],
            packages: vec![EmitPackage {
                name: "certifi".into(),
                version: "2025.4.26".into(),
                deps: vec![],
                wheels,
            }],
        }
    }

    #[test]
    fn emitter_returns_four_strings() {
        let out = StringTemplateEmitter.emit(&empty_input());
        let _ = out.buck;
        let _ = out.muntjac_bzl;
        let _ = out.config_buck;
        let _ = out.package_file;
    }

    #[test]
    fn empty_input_buck_has_header_and_load() {
        let out = StringTemplateEmitter.emit(&empty_input());
        assert!(out.buck.starts_with("##\n## @generated by muntjac\n## Do not edit by hand.\n##\n\n"),
            "missing or malformed BUCK header:\n{}", out.buck);
        assert!(out.buck.contains(r#"load("//third-party/python:muntjac.bzl", "pypi_package")"#),
            "missing or wrong load() line:\n{}", out.buck);
    }

    #[test]
    fn single_package_buck_contains_pypi_package_call() {
        let out = StringTemplateEmitter.emit(&single_package_input());
        assert!(out.buck.contains("pypi_package("));
        assert!(out.buck.contains(r#"name = "certifi""#));
        assert!(out.buck.contains(r#"version = "2025.4.26""#));
        assert!(out.buck.contains(r#""py312-linux-x86_64-gnu":"#));
        assert!(out.buck.contains("sha256:0123abcd"));
        assert!(out.buck.contains(r#"visibility = ["PUBLIC"]"#));
    }

    #[test]
    fn two_packages_emitted_alphabetically() {
        let mut input = single_package_input();
        let mut wheels = BTreeMap::new();
        wheels.insert(
            input.configs[0].clone(),
            EmitWheel {
                url: "https://example.com/alpha-1.0-py3-none-any.whl".into(),
                hash: "sha256:aaaa".into(),
            },
        );
        input.packages.insert(0, EmitPackage {
            name: "alpha".into(),
            version: "1.0".into(),
            deps: vec![],
            wheels,
        });
        let out = StringTemplateEmitter.emit(&input);
        let alpha_pos = out.buck.find("name = \"alpha\"").expect("alpha not emitted");
        let certifi_pos = out.buck.find("name = \"certifi\"").expect("certifi not emitted");
        assert!(alpha_pos < certifi_pos, "alpha must precede certifi in output:\n{}", out.buck);
    }
}
