//! Hand-rolled string-writer implementation of `BuckEmitter`.

use std::collections::BTreeSet;
use std::fmt::Write;

use super::emit::{BuckEmitter, ConfigName, EmitDeps, EmitInput, EmitOutput, EmitPackage};

pub struct StringTemplateEmitter;

impl BuckEmitter for StringTemplateEmitter {
    fn emit(&self, input: &EmitInput) -> EmitOutput {
        EmitOutput {
            buck: emit_buck(input),
            muntjac_bzl: emit_muntjac_bzl(input),
            config_buck: emit_config_buck(input),
            package_file: emit_package_file(input),
        }
    }
}

fn emit_buck(input: &EmitInput) -> String {
    let mut s = String::new();
    writeln!(s, "##").unwrap();
    writeln!(s, "## @generated by muntjac").unwrap();
    writeln!(s, "## Do not edit by hand.").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "load(\"//{}:muntjac.bzl\", \"pypi_package\")",
        input.third_party_dir
    )
    .unwrap();

    // Packages are pre-sorted by (name, version) in EmitInput; defensive sort anyway.
    let mut sorted_pkgs: Vec<&EmitPackage> = input.packages.iter().collect();
    sorted_pkgs.sort_by(|a, b| a.name.cmp(&b.name).then(a.version.cmp(&b.version)));

    for pkg in sorted_pkgs {
        writeln!(s).unwrap();
        write_pypi_package(&mut s, pkg, &input.third_party_dir);
    }
    s
}

fn emit_muntjac_bzl(input: &EmitInput) -> String {
    let mut s = String::new();
    let tpd = &input.third_party_dir;

    // Header: @generated tag + wiring contract for consumers.
    writeln!(s, "##").unwrap();
    writeln!(s, "## @generated by muntjac").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s, "## Wiring contract for consumers:").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s, "##   One-time project setup — add to your root PACKAGE:").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s, "##     load(\"//{}:wiring.bzl\", \"setup_muntjac\")", tpd).unwrap();
    writeln!(s, "##     setup_muntjac()").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(
        s,
        "##   This registers buck2's cfg_constructor and auto-routes the host"
    )
    .unwrap();
    writeln!(s, "##   OS+CPU to the matching muntjac platform constraint.").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(
        s,
        "##   To pick a python version, set a per-binary modifier or a"
    )
    .unwrap();
    writeln!(s, "##   root-PACKAGE default:").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s, "##     # per-binary").unwrap();
    writeln!(s, "##     python_binary(").unwrap();
    writeln!(s, "##         name = \"service\",").unwrap();
    writeln!(s, "##         modifiers = [\"//{}/config:py312\"],", tpd).unwrap();
    writeln!(s, "##         deps = [\"//{}:numpy\"],", tpd).unwrap();
    writeln!(s, "##         main = \"main.py\",").unwrap();
    writeln!(s, "##     )").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s, "##     # root PACKAGE default").unwrap();
    writeln!(
        s,
        "##     load(\"@prelude//cfg/modifier:set_cfg_modifiers.bzl\", \"set_cfg_modifiers\")"
    )
    .unwrap();
    writeln!(
        s,
        "##     set_cfg_modifiers([\"//{}/config:py312\"])",
        tpd
    )
    .unwrap();
    writeln!(s, "##").unwrap();

    // Available python constraints derived from configs (sorted set).
    let py_constraints: BTreeSet<String> = input
        .configs
        .iter()
        .filter_map(|c| c.as_str().split('-').next().map(|p| p.to_string()))
        .filter(|p| p.starts_with("py"))
        .collect();
    let py_list: Vec<&str> = py_constraints.iter().map(|p| p.as_str()).collect();
    writeln!(
        s,
        "## Available muntjac python constraints: {}",
        py_list.join(", ")
    )
    .unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s).unwrap();

    // _CONFIGS list, sorted lex.
    let mut sorted_configs: Vec<&ConfigName> = input.configs.iter().collect();
    sorted_configs.sort();
    writeln!(s, "_CONFIGS = [").unwrap();
    for cfg in &sorted_configs {
        writeln!(s, "    \"{}\",", cfg).unwrap();
    }
    writeln!(s, "]").unwrap();
    writeln!(s).unwrap();

    // pypi_package macro — uses native.<rule> for http_file, prebuilt_python_library,
    // alias. Replaces expect(...) with explicit if/fail. sha256 stripping handled
    // inside the macro to match uv.lock's "sha256:" prefix convention.
    writeln!(
        s,
        "def pypi_package(name, version, wheels, deps = [], visibility = None, **kwargs):"
    )
    .unwrap();
    writeln!(
        s,
        "    unknown = [cfg for cfg in wheels.keys() if cfg not in _CONFIGS]"
    )
    .unwrap();
    writeln!(s, "    if unknown:").unwrap();
    writeln!(
        s,
        "        fail(\"unknown config(s) in {{}}: {{}}\".format(name, unknown))"
    )
    .unwrap();
    writeln!(s).unwrap();
    writeln!(s, "    for cfg, wheel in wheels.items():").unwrap();
    writeln!(s, "        url, sha = wheel").unwrap();
    writeln!(s, "        if sha.startswith(\"sha256:\"):").unwrap();
    writeln!(s, "            sha = sha[len(\"sha256:\"):]").unwrap();
    writeln!(
        s,
        "        wheel_name = \"{{}}-{{}}-{{}}-wheel\".format(name, version, cfg)"
    )
    .unwrap();
    writeln!(s, "        native.http_file(").unwrap();
    writeln!(s, "            name = wheel_name,").unwrap();
    writeln!(s, "            sha256 = sha,").unwrap();
    writeln!(s, "            urls = [url],").unwrap();
    writeln!(s, "            visibility = [],").unwrap();
    writeln!(s, "        )").unwrap();
    writeln!(s, "        native.prebuilt_python_library(").unwrap();
    writeln!(
        s,
        "            name = \"{{}}-{{}}__{{}}\".format(name, version, cfg),"
    )
    .unwrap();
    writeln!(s, "            binary_src = \":\" + wheel_name,").unwrap();
    writeln!(s, "            deps = deps,").unwrap();
    writeln!(s, "            visibility = [],").unwrap();
    writeln!(s, "        )").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "    native.alias(").unwrap();
    writeln!(s, "        name = \"{{}}-{{}}\".format(name, version),").unwrap();
    writeln!(s, "        actual = select({{").unwrap();
    writeln!(
        s,
        "            \"//{}/config:\" + cfg: \":{{}}-{{}}__{{}}\".format(name, version, cfg)",
        tpd
    )
    .unwrap();
    writeln!(s, "            for cfg in wheels.keys()").unwrap();
    writeln!(s, "        }}),").unwrap();
    writeln!(s, "        visibility = [],").unwrap();
    writeln!(s, "    )").unwrap();
    writeln!(s, "    native.alias(").unwrap();
    writeln!(s, "        name = name,").unwrap();
    writeln!(s, "        actual = \":{{}}-{{}}\".format(name, version),").unwrap();
    writeln!(
        s,
        "        visibility = visibility if visibility != None else [\"PUBLIC\"],"
    )
    .unwrap();
    writeln!(s, "    )").unwrap();
    s
}

fn emit_config_buck(input: &EmitInput) -> String {
    let mut s = String::new();
    writeln!(s, "##").unwrap();
    writeln!(s, "## @generated by muntjac").unwrap();
    writeln!(s, "## Do not edit by hand.").unwrap();
    writeln!(s, "##").unwrap();

    let mut sorted_configs: Vec<&ConfigName> = input.configs.iter().collect();
    sorted_configs.sort();

    // Per-cell config_setting blocks.
    for cfg in &sorted_configs {
        let (py_part, plat_part) = split_config(cfg.as_str());
        writeln!(s).unwrap();
        writeln!(s, "config_setting(").unwrap();
        writeln!(s, "    name = \"{}\",", cfg).unwrap();
        writeln!(s, "    constraint_values = [").unwrap();
        writeln!(
            s,
            "        \"//{}/config:{}\",",
            input.third_party_dir, py_part
        )
        .unwrap();
        writeln!(
            s,
            "        \"//{}/config:{}\",",
            input.third_party_dir, plat_part
        )
        .unwrap();
        writeln!(s, "    ],").unwrap();
        writeln!(s, ")").unwrap();
    }

    // Per-axis constraint_setting + constraint_value blocks.
    let mut pys: BTreeSet<&str> = BTreeSet::new();
    let mut plats: BTreeSet<&str> = BTreeSet::new();
    for cfg in &sorted_configs {
        let (py, plat) = split_config(cfg.as_str());
        pys.insert(py);
        plats.insert(plat);
    }

    writeln!(s).unwrap();
    writeln!(s, "constraint_setting(name = \"python_version\")").unwrap();
    for py in &pys {
        writeln!(
            s,
            "constraint_value(name = \"{}\", constraint_setting = \":python_version\")",
            py
        )
        .unwrap();
    }

    writeln!(s).unwrap();
    writeln!(s, "constraint_setting(name = \"platform\")").unwrap();
    for plat in &plats {
        writeln!(
            s,
            "constraint_value(name = \"{}\", constraint_setting = \":platform\")",
            plat
        )
        .unwrap();
    }

    s
}

fn emit_package_file(_input: &EmitInput) -> String {
    let mut s = String::new();
    writeln!(s, "##").unwrap();
    writeln!(s, "## @generated by muntjac").unwrap();
    writeln!(s, "## Do not edit by hand.").unwrap();
    writeln!(s, "##").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "# Wires python_version + platform constraints so consumers' python_binary"
    )
    .unwrap();
    writeln!(
        s,
        "# selects the right wheel via the alias-with-select pattern."
    )
    .unwrap();
    writeln!(s, "#").unwrap();
    writeln!(
        s,
        "# S3 emits a minimal PACKAGE; full set_cfg_modifiers wiring lands in S4"
    )
    .unwrap();
    writeln!(
        s,
        "# once multi-platform select() has been exercised against a buck2 build."
    )
    .unwrap();
    writeln!(s, "# (placeholder)").unwrap();
    s
}

/// Split a ConfigName like "py312-linux-x86_64-gnu" into ("py312", "linux-x86_64-gnu").
fn split_config(name: &str) -> (&str, &str) {
    name.split_once('-')
        .expect("ConfigName has form pyXY-<platform>")
}

fn write_pypi_package(s: &mut String, pkg: &EmitPackage, pkg_third_party_dir: &str) {
    writeln!(s, "pypi_package(").unwrap();
    writeln!(s, "    name = \"{}\",", pkg.name).unwrap();
    writeln!(s, "    version = \"{}\",", pkg.version).unwrap();
    // Task 9: Render deps for Uniform variant (restored from S3).
    // Task 10: PerCell variant fills in select() rendering.
    match &pkg.deps {
        EmitDeps::Uniform(v) => {
            if v.is_empty() {
                writeln!(s, "    deps = [],").unwrap();
            } else {
                writeln!(s, "    deps = [").unwrap();
                for dep in v {
                    writeln!(s, "        \"{}\",", dep).unwrap();
                }
                writeln!(s, "    ],").unwrap();
            }
        }
        EmitDeps::PerCell(per_cell) => {
            writeln!(s, "    deps = select({{").unwrap();
            for (cell, deps_v) in per_cell {
                // select() branch keys are config target labels in the same cell.
                let key = format!("//{}/config:{}", pkg_third_party_dir, cell);
                if deps_v.is_empty() {
                    writeln!(s, "        \"{}\": [],", key).unwrap();
                } else {
                    writeln!(s, "        \"{}\": [", key).unwrap();
                    for d in deps_v {
                        writeln!(s, "            \"{}\",", d).unwrap();
                    }
                    writeln!(s, "        ],").unwrap();
                }
            }
            writeln!(s, "    }}),").unwrap();
        }
    }
    writeln!(s, "    wheels = {{").unwrap();
    for (cfg, wheel) in &pkg.wheels {
        writeln!(
            s,
            "        \"{}\": (\"{}\", \"{}\"),",
            cfg, wheel.url, wheel.hash
        )
        .unwrap();
    }
    writeln!(s, "    }},").unwrap();
    writeln!(s, "    visibility = [\"PUBLIC\"],").unwrap();
    writeln!(s, ")").unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::buck::emit::ConfigName;
    use crate::buck::emit::{EmitPackage, EmitWheel};
    use std::collections::BTreeMap;

    fn empty_input() -> EmitInput {
        EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![ConfigName::new("3.12", "linux-x86_64-gnu")],
            packages: vec![],
        }
    }

    fn single_package_input() -> EmitInput {
        let cfg = ConfigName::new("3.12", "linux-x86_64-gnu");
        let mut wheels = BTreeMap::new();
        wheels.insert(
            cfg.clone(),
            EmitWheel {
                url: "https://files.pythonhosted.org/p/certifi-2025.4.26-py3-none-any.whl".into(),
                hash: "sha256:0123abcd".into(),
            },
        );
        EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![cfg],
            packages: vec![EmitPackage {
                name: "certifi".into(),
                version: "2025.4.26".into(),
                deps: EmitDeps::Uniform(vec![]),
                wheels,
            }],
        }
    }

    #[test]
    fn emitter_returns_four_strings() {
        let out = StringTemplateEmitter.emit(&empty_input());
        let _ = out.buck;
        let _ = out.muntjac_bzl;
        let _ = out.config_buck;
        let _ = out.package_file;
    }

    #[test]
    fn empty_input_buck_has_header_and_load() {
        let out = StringTemplateEmitter.emit(&empty_input());
        assert!(
            out.buck
                .starts_with("##\n## @generated by muntjac\n## Do not edit by hand.\n##\n\n"),
            "missing or malformed BUCK header:\n{}",
            out.buck
        );
        assert!(
            out.buck
                .contains(r#"load("//third-party/python:muntjac.bzl", "pypi_package")"#),
            "missing or wrong load() line:\n{}",
            out.buck
        );
    }

    #[test]
    fn single_package_buck_contains_pypi_package_call() {
        let out = StringTemplateEmitter.emit(&single_package_input());
        assert!(out.buck.contains("pypi_package("));
        assert!(out.buck.contains(r#"name = "certifi""#));
        assert!(out.buck.contains(r#"version = "2025.4.26""#));
        assert!(out.buck.contains(r#""py312-linux-x86_64-gnu":"#));
        assert!(out.buck.contains("sha256:0123abcd"));
        assert!(out.buck.contains(r#"visibility = ["PUBLIC"]"#));
    }

    #[test]
    fn muntjac_bzl_has_header_and_configs_list() {
        let out = StringTemplateEmitter.emit(&empty_input());
        assert!(
            out.muntjac_bzl
                .starts_with("##\n## @generated by muntjac\n##\n"),
            "missing muntjac.bzl header:\n{}",
            out.muntjac_bzl
        );
        // S4: header now includes the wiring contract for consumers.
        assert!(
            out.muntjac_bzl
                .contains("## Wiring contract for consumers:"),
            "missing wiring contract block:\n{}",
            out.muntjac_bzl
        );
        assert!(out.muntjac_bzl.contains("setup_muntjac()"));
        assert!(out.muntjac_bzl.contains("set_cfg_modifiers"));
        assert!(out.muntjac_bzl.contains("_CONFIGS = ["));
        assert!(out.muntjac_bzl.contains("    \"py312-linux-x86_64-gnu\","));
        assert!(out.muntjac_bzl.contains("def pypi_package("));
        // S4: native.<rule> form, no bogus load()s.
        assert!(out.muntjac_bzl.contains("native.prebuilt_python_library"));
        assert!(out.muntjac_bzl.contains("native.http_file"));
        assert!(!out.muntjac_bzl.contains("expect("));
        assert!(out.muntjac_bzl.contains("if unknown:"));
        assert!(out.muntjac_bzl.contains("//third-party/python/config:"));
    }

    #[test]
    fn muntjac_bzl_configs_list_sorted_lex() {
        let mut input = empty_input();
        input.configs = vec![
            ConfigName::new("3.12", "linux-x86_64-gnu"),
            ConfigName::new("3.11", "linux-x86_64-gnu"),
        ];
        let out = StringTemplateEmitter.emit(&input);
        let p311 = out
            .muntjac_bzl
            .find("\"py311-linux-x86_64-gnu\"")
            .expect("py311 missing");
        let p312 = out
            .muntjac_bzl
            .find("\"py312-linux-x86_64-gnu\"")
            .expect("py312 missing");
        assert!(p311 < p312, "_CONFIGS not sorted:\n{}", out.muntjac_bzl);
    }

    #[test]
    fn config_buck_declares_per_cell_settings() {
        let mut input = empty_input();
        input.configs = vec![
            ConfigName::new("3.11", "linux-x86_64-gnu"),
            ConfigName::new("3.12", "linux-x86_64-gnu"),
        ];
        let out = StringTemplateEmitter.emit(&input);
        assert!(
            out.config_buck
                .starts_with("##\n## @generated by muntjac\n## Do not edit by hand.\n##\n\n"),
            "missing config/BUCK header:\n{}",
            out.config_buck
        );
        assert!(out.config_buck.contains("config_setting("));
        assert!(
            out.config_buck
                .contains(r#"name = "py311-linux-x86_64-gnu""#)
        );
        assert!(
            out.config_buck
                .contains(r#"name = "py312-linux-x86_64-gnu""#)
        );
        assert!(
            out.config_buck
                .contains(r#"constraint_setting(name = "python_version")"#)
        );
        assert!(
            out.config_buck
                .contains(r#"constraint_value(name = "py311""#)
        );
        assert!(
            out.config_buck
                .contains(r#"constraint_value(name = "py312""#)
        );
        assert!(
            out.config_buck
                .contains(r#"constraint_setting(name = "platform")"#)
        );
        assert!(
            out.config_buck
                .contains(r#"constraint_value(name = "linux-x86_64-gnu""#)
        );
    }

    #[test]
    fn config_buck_settings_sorted_by_name() {
        let mut input = empty_input();
        input.configs = vec![
            ConfigName::new("3.12", "linux-x86_64-gnu"),
            ConfigName::new("3.11", "linux-x86_64-gnu"),
        ];
        let out = StringTemplateEmitter.emit(&input);
        let p311 = out
            .config_buck
            .find(r#"name = "py311-linux-x86_64-gnu""#)
            .expect("py311 missing");
        let p312 = out
            .config_buck
            .find(r#"name = "py312-linux-x86_64-gnu""#)
            .expect("py312 missing");
        assert!(
            p311 < p312,
            "config_settings must be sorted:\n{}",
            out.config_buck
        );
    }

    #[test]
    fn package_file_has_header_and_placeholder_comment() {
        let out = StringTemplateEmitter.emit(&empty_input());
        assert!(
            out.package_file
                .starts_with("##\n## @generated by muntjac\n## Do not edit by hand.\n##\n\n"),
            "missing PACKAGE header:\n{}",
            out.package_file
        );
        assert!(
            out.package_file.contains("set_cfg_modifiers"),
            "PACKAGE should reference the future S4 wiring"
        );
        assert!(
            out.package_file.contains("S4") || out.package_file.contains("placeholder"),
            "PACKAGE should explicitly mark itself as a placeholder"
        );
    }

    #[test]
    fn two_packages_emitted_alphabetically() {
        let mut input = single_package_input();
        let mut wheels = BTreeMap::new();
        wheels.insert(
            input.configs[0].clone(),
            EmitWheel {
                url: "https://example.com/alpha-1.0-py3-none-any.whl".into(),
                hash: "sha256:aaaa".into(),
            },
        );
        input.packages.insert(
            0,
            EmitPackage {
                name: "alpha".into(),
                version: "1.0".into(),
                deps: EmitDeps::Uniform(vec![]),
                wheels,
            },
        );
        let out = StringTemplateEmitter.emit(&input);
        let alpha_pos = out
            .buck
            .find("name = \"alpha\"")
            .expect("alpha not emitted");
        let certifi_pos = out
            .buck
            .find("name = \"certifi\"")
            .expect("certifi not emitted");
        assert!(
            alpha_pos < certifi_pos,
            "alpha must precede certifi in output:\n{}",
            out.buck
        );
    }

    fn multi_package_input() -> EmitInput {
        let cfg_311 = ConfigName::new("3.11", "linux-x86_64-gnu");
        let cfg_312 = ConfigName::new("3.12", "linux-x86_64-gnu");

        let mut requests_wheels = BTreeMap::new();
        requests_wheels.insert(
            cfg_311.clone(),
            EmitWheel {
                url: "https://example.com/requests-2.32.3-py3-none-any.whl".into(),
                hash: "sha256:rrrr".into(),
            },
        );
        requests_wheels.insert(
            cfg_312.clone(),
            EmitWheel {
                url: "https://example.com/requests-2.32.3-py3-none-any.whl".into(),
                hash: "sha256:rrrr".into(),
            },
        );

        let mut idna_wheels = BTreeMap::new();
        idna_wheels.insert(
            cfg_311.clone(),
            EmitWheel {
                url: "https://example.com/idna-3.7-py3-none-any.whl".into(),
                hash: "sha256:iiii".into(),
            },
        );
        idna_wheels.insert(
            cfg_312.clone(),
            EmitWheel {
                url: "https://example.com/idna-3.7-py3-none-any.whl".into(),
                hash: "sha256:iiii".into(),
            },
        );

        EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![cfg_311, cfg_312],
            packages: vec![
                EmitPackage {
                    name: "idna".into(),
                    version: "3.7".into(),
                    deps: EmitDeps::Uniform(vec![]),
                    wheels: idna_wheels,
                },
                EmitPackage {
                    name: "requests".into(),
                    version: "2.32.3".into(),
                    deps: EmitDeps::Uniform(vec![":idna".into()]),
                    wheels: requests_wheels,
                },
            ],
        }
    }

    #[test]
    fn snapshot_empty_buck() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&empty_input()).buck);
    }

    #[test]
    fn snapshot_empty_muntjac_bzl() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&empty_input()).muntjac_bzl);
    }

    #[test]
    fn snapshot_empty_config_buck() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&empty_input()).config_buck);
    }

    #[test]
    fn snapshot_empty_package_file() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&empty_input()).package_file);
    }

    #[test]
    fn snapshot_single_package_buck() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&single_package_input()).buck);
    }

    #[test]
    fn snapshot_multi_package_buck() {
        insta::assert_snapshot!(StringTemplateEmitter.emit(&multi_package_input()).buck);
    }

    #[test]
    fn snapshot_multi_package_muntjac_bzl() {
        insta::assert_snapshot!(
            StringTemplateEmitter
                .emit(&multi_package_input())
                .muntjac_bzl
        );
    }

    #[test]
    fn snapshot_multi_package_config_buck() {
        insta::assert_snapshot!(
            StringTemplateEmitter
                .emit(&multi_package_input())
                .config_buck
        );
    }

    #[test]
    fn renders_per_cell_deps_as_select() {
        let cells: Vec<ConfigName> = vec![
            ConfigName::new("3.11", "linux-x86_64-gnu"),
            ConfigName::new("3.12", "linux-x86_64-gnu"),
        ];

        let mut per_cell: BTreeMap<ConfigName, Vec<String>> = BTreeMap::new();
        per_cell.insert(
            cells[0].clone(),
            vec![":foo".into(), ":typing-extensions".into()],
        );
        per_cell.insert(cells[1].clone(), vec![":foo".into()]);

        let mut wheels: BTreeMap<ConfigName, EmitWheel> = BTreeMap::new();
        for cell in &cells {
            wheels.insert(
                cell.clone(),
                EmitWheel {
                    url: format!("https://example.com/rich-13.0-{}.whl", cell),
                    hash: "sha256:rich".into(),
                },
            );
        }

        let input = EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: cells,
            packages: vec![EmitPackage {
                name: "rich".into(),
                version: "13.0".into(),
                deps: EmitDeps::PerCell(per_cell),
                wheels,
            }],
        };

        let out = StringTemplateEmitter.emit(&input);
        insta::assert_snapshot!("per_cell_deps_select", out.buck);
    }

    #[test]
    fn muntjac_bzl_emits_full_macro_with_header() {
        let input = EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![
                ConfigName::new("3.11", "linux-x86_64-gnu"),
                ConfigName::new("3.12", "linux-x86_64-gnu"),
            ],
            packages: vec![],
        };

        let out = StringTemplateEmitter.emit(&input);
        insta::assert_snapshot!("muntjac_bzl_with_header_and_native", out.muntjac_bzl);
    }

    #[test]
    fn renders_uniform_deps_as_plain_list() {
        let cell = ConfigName::new("3.12", "linux-x86_64-gnu");
        let mut wheels: BTreeMap<ConfigName, EmitWheel> = BTreeMap::new();
        wheels.insert(
            cell.clone(),
            EmitWheel {
                url: "https://example.com/requests-2.32.3-py3-none-any.whl".into(),
                hash: "sha256:req".into(),
            },
        );

        let input = EmitInput {
            tree: "default".into(),
            third_party_dir: "third-party/python".into(),
            configs: vec![cell],
            packages: vec![EmitPackage {
                name: "requests".into(),
                version: "2.32.3".into(),
                deps: EmitDeps::Uniform(vec![":certifi".into(), ":idna".into()]),
                wheels,
            }],
        };

        let out = StringTemplateEmitter.emit(&input);
        insta::assert_snapshot!("uniform_deps_plain_list", out.buck);
    }
}
